# Introduction to Machine Learning (SWE4003)

This content is practice material for the Introduction to Machine Learning (SWE4003) course. All content is based on: https://apxml.com/courses/getting-started-with-pytorch/

First, let's ensure PyTorch is correctly installed and accessible in your Python environment.
Open your Python interpreter or a Jupyter Notebook and run the following commands:

In [2]:
import torch
import numpy as np # We'll use NumPy for comparison later

# Print PyTorch version
print(f"PyTorch Version: {torch.__version__}")

# Check if CUDA (GPU support) is available using if-else statement
# ############## Your Code Here ##############
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
# ############################################

print(f"Default device: {device}")

PyTorch Version: 2.10.0+cpu
Default device: cpu


## [1] Creating Tensors
Let's practice creating Tensors using various methods introduced earlier.

In [3]:
# 1. From Python Lists: Create a 2x3 tensor from a nested Python list.

# ############## Your Code Here ##############
data = [[1,2,3],[4,5,6]]
tensor_from_list = torch.tensor(data)
# ############################################

print("Tensor from list:")
print(tensor_from_list)
print(f"Shape: {tensor_from_list.shape}")
print(f"Data type: {tensor_from_list.dtype}")

Tensor from list:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Data type: torch.int64


In [4]:
# 2. Specifying Data Type: Create the same tensor but explicitly set the data type to 32-bit floating point.

# ############## Your Code Here ##############
tensor_float = torch.tensor(data, dtype=torch.float32)
# ############################################

print("\nTensor with float32 dtype:")
print(tensor_float)
print(f"Shape: {tensor_float.shape}")
print(f"Data type: {tensor_float.dtype}")


Tensor with float32 dtype:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape: torch.Size([2, 3])
Data type: torch.float32


In [5]:
# 3. Using Factory Functions: Create tensors with specific shapes and initial values.

# ############## Your Code Here ##############
# Create a 3x4 tensor of zeros
zeros_tensor = torch.zeros(3,4)

# Create a 2x2 tensor of ones with 32-bit integer type
ones_tensor_int = torch.ones(2,2, dtype=torch.int32)

# Create a 1D tensor representing a range of numbers
range_tensor = torch.arange(5)

# Create a 2x3 tensor with random values (uniform distribution 0 to 1)
rand_tensor = torch.rand(2,3)
# ############################################

print("\nZeros Tensor (3x4):")
print(zeros_tensor)
print("\nOnes Tensor (2x2, 32-bit int):")
print(ones_tensor_int)
print("\nRange Tensor (0 to 4):")
print(range_tensor)
print("\nRandom Tensor (2x3):")
print(rand_tensor)


Zeros Tensor (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones Tensor (2x2, 32-bit int):
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

Range Tensor (0 to 4):
tensor([0, 1, 2, 3, 4])

Random Tensor (2x3):
tensor([[0.9874, 0.5358, 0.6103],
        [0.5710, 0.9538, 0.8294]])


## [2] Basic Tensor Operations

Now, let's perform some fundamental operations on the tensors we've created.

In [7]:
# Create the 2x2 float32 tensor created earlier
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
# Create a 2x2 tensor of ones
b = torch.ones(2,2)

print("Tensor 'a':")
print(a)
print("Tensor 'b':")
print(b)

# ############## Your Code Here ##############
# Element-wise addition of a and b (2 version)
sum_tensor1 = a + b
sum_tensor2 = torch.add(a, b)

# Element-wise multiplication of a and b (2 version)
prod_tensor1 = a * b
prod_tensor2 = torch.mul(a, b)

# Scalar multiplication: a times 3
scalar_mult = a*3

print(f"\n'a' before in-place add: ID {id(a)}")
# In-place addition (modifies 'a')
# WRITE CODE IN THIS LINE !! In-place addition (modifies 'a')

print("'a' after in-place add:")
print(a)
print(f"'a' after in-place add: ID {id(a)}") # ID remains the same

# Matrix multiplication
# Ensure dimensions are compatible for matrix multiplication
# Let's create compatible random tensors: x (2x3), y (3x2)
x = torch.rand(2,3)
y = torch.rand(3,2)

# Multiply x and y (2 version)
matmul_result1 = x @ y
matmul_result2 = torch.matmul(x, y)
# ############################################

print("\nElement-wise Sum:")
print(sum_tensor1)
print(sum_tensor2)
print("\nElement-wise Product:")
print(prod_tensor1)
print(prod_tensor2)
print("\nScalar Multiplication:")
print(scalar_mult)
print(f"Result shape: {matmul_result1.shape}")
print(f"Result shape: {matmul_result2.shape}")
print(matmul_result1)
print(matmul_result2)

Tensor 'a':
tensor([[1., 2.],
        [3., 4.]])
Tensor 'b':
tensor([[1., 1.],
        [1., 1.]])

'a' before in-place add: ID 139386549071344
'a' after in-place add:
tensor([[1., 2.],
        [3., 4.]])
'a' after in-place add: ID 139386549071344

Element-wise Sum:
tensor([[2., 3.],
        [4., 5.]])
tensor([[2., 3.],
        [4., 5.]])

Element-wise Product:
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])

Scalar Multiplication:
tensor([[ 3.,  6.],
        [ 9., 12.]])
Result shape: torch.Size([2, 2])
Result shape: torch.Size([2, 2])
tensor([[0.7178, 0.6275],
        [0.5474, 0.4580]])
tensor([[0.7178, 0.6275],
        [0.5474, 0.4580]])
