# Introduction to Machine Learning (SWE4003)

This content is practice material for the Introduction to Machine Learning (SWE4003) course. All content is based on: https://apxml.com/courses/getting-started-with-pytorch/

Practice tensor manipulation techniques, including indexing, reshaping, combining, broadcasting, data types, and moving tensors between devices. Working through these examples is the best way to solidify your understanding. Ensure PyTorch is imported.

In [ ]:
import torch
import numpy as np

# Check if CUDA is available and set the device
# ############## Your Code Here ##############
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# ############################################
print(f"Using device: {device}")

Using device: cuda


### [1] Indexing and Slicing Practice

Indexing and slicing are fundamental for accessing and modifying parts of your tensors. Let's try selecting specific data points.

In [ ]:
# Create a sample 2D tensor (3 rows, 4 columns)
# ############## Your Code Here ##############
tensor_2d = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# ############################################
print("Original Tensor:\n", tensor_2d)

# Select the element at row index 1, column index 2
# ############## Your Code Here ##############
element = tensor_2d[1,2]
# ############################################
print("\nElement at row index 1, column index 2:", element)
print("Value:", element.item()) # Use .item() to get the Python number

# Select the row index 1 of tensor_2d
# ############## Your Code Here ##############
row_1 = tensor_2d[1]
# ############################################
print("\nSecond row (index 1):\n", row_1)

# Alternative using slicing (selects row 1, all columns) of tensor_2d
# ############## Your Code Here ##############
row_1_alt = tensor_2d[1,:]
# ############################################
print("\nSecond row (alternative):\n", row_1_alt)

# Select all rows, column index 2 of tensor_2d
# ############## Your Code Here ##############
col_2 = tensor_2d[:,2]
# ############################################
print("\nThird column (index 2):\n", col_2)

# Create a boolean mask to select all elements in tensor_2d greater than 7
# ############## Your Code Here ##############
mask = tensor_2d>7
# ############################################
print("\nBoolean mask (tensor > 7):\n", mask)

# Apply the mask
# ############## Your Code Here ##############
selected_elements = tensor_2d[mask]
# ############################################
print("\nElements greater than 7:\n", selected_elements)

Original Tensor:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Element at row index 1, column index 2: tensor(7)
Value: 7

Second row (index 1):
 tensor([5, 6, 7, 8])

Second row (alternative):
 tensor([5, 6, 7, 8])

Third column (index 2):
 tensor([ 3,  7, 11, 15])

Boolean mask (tensor > 7):
 tensor([[False, False, False, False],
        [False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

Elements greater than 7:
 tensor([ 8,  9, 10, 11, 12, 13, 14, 15, 16])


### [2] Reshaping and Rearranging Practice

Changing a tensor's shape without altering its data is common, especially when preparing inputs for different neural network layers.

In [ ]:
# Create a 1D tensor with 12 elements and reshape it into a 3x4 tensor.
# Reshape using reshape()
# ############## Your Code Here ##############
reshaped_tensor = torch.arange(12)
# ############################################
print("\nReshaped to 3x4:\n", reshaped_tensor)

# Reshape using view()
# ############## Your Code Here ##############
view_tensor = reshaped_tensor.view(3,4)
# ############################################

print("\nViewed as 3x4:\n", view_tensor)


Reshaped to 3x4:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Viewed as 3x4:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [30]:
# Given the reshaped_tensor (3x4), use permute to swap its dimensions, resulting in a 4x3 tensor.
# Original 3x4 tensor
print("\nOriginal 3x4 Tensor:\n", reshaped_tensor)

# Swap dimensions 0 and 1
# ############## Your Code Here ##############
permuted_tensor = reshaped_tensor.permute(-1)
# ############################################
print("\nPermuted to 4x3:\n", permuted_tensor)
print("Original shape:", reshaped_tensor.shape)
print("Permuted shape:", permuted_tensor.shape)

# permute is useful for tasks like changing image dimension order (e.g., from Channels X Height X Width to Height X Width X Channels).


Original 3x4 Tensor:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Permuted to 4x3:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])
Permuted shape: torch.Size([12])


### [3] Joining and Splitting Practice

Combining tensors or breaking them apart is often needed when dealing with batches or different feature sets.

In [ ]:
# Create two 2x3 tensors
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print("\nTensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)

# Concatenate two tensors by stacking rows
# ############## Your Code Here ##############
concatenated_rows = torch.cat((tensor_a, tensor_b), dim = 0)
# ############################################
print("\nConcatenated along rows (dim=0):\n", concatenated_rows)
print("Shape:", concatenated_rows.shape) # Should be 4x3

# Concatenate two tensors by stacking columns.
# ############## Your Code Here ##############
concatenated_cols = torch.cat((tensor_a, tensor_b), dim = 1)
# ############################################
print("\nConcatenated along columns (dim=1):\n", concatenated_cols)
print("Shape:", concatenated_cols.shape) # Should be 2x6

# Use stack to combine two tensors into a new tensor with shape 2x2x3.
# Stack along dimension 0
# ############## Your Code Here ##############
stacked_tensor = torch.stack((tensor_a, tensor_b), dim = 0)
# ############################################
print("\nStacked tensors (dim=0):\n", stacked_tensor)
print("Shape:", stacked_tensor.shape) # Should be 2x2x3

# Stack along dimension 1
# ############## Your Code Here ##############
stacked_tensor_dim1 = torch.stack((tensor_a, tensor_b), dim = 1)
# ############################################
print("\nStacked tensors (dim=1):\n", stacked_tensor_dim1)
print("Shape:", stacked_tensor_dim1.shape) # Should be 2x2x3


Tensor A:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor B:
 tensor([[ 7,  8,  9],
        [10, 11, 12]])

Concatenated along rows (dim=0):
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
Shape: torch.Size([4, 3])

Concatenated along columns (dim=1):
 tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])
Shape: torch.Size([2, 6])

Stacked tensors (dim=0):
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Shape: torch.Size([2, 2, 3])

Stacked tensors (dim=1):
 tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])
Shape: torch.Size([2, 2, 3])


In [ ]:
# Create a 6x4 tensor and split it into three equal chunks along dimension 0
tensor_to_split = torch.arange(24).reshape(6, 4)
print("\nTensor to split (6x4):\n", tensor_to_split)

# Split into 3 chunks along dimension 0
# ############## Your Code Here ##############
chunks = torch.chunk(tensor_to_split, 3, dim = 0)
# ############################################
print("\nSplit into 3 chunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i} (shape {chunk.shape}):\n", chunk)


Tensor to split (6x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])

Split into 3 chunks:
Chunk 0 (shape torch.Size([2, 4])):
 tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
Chunk 1 (shape torch.Size([2, 4])):
 tensor([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])
Chunk 2 (shape torch.Size([2, 4])):
 tensor([[16, 17, 18, 19],
        [20, 21, 22, 23]])


### [4] Broadcasting Practice

Broadcasting simplifies operations between tensors of different shapes.

In [ ]:
# Create a 3x3 tensor and a 1x3 tensor (row vector). Add them together.
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# ############## Your Code Here ##############
row_vector = torch.tensor([[10, 11, 12]])
# ############################################
print("\nMatrix (3x3):\n", matrix)
print("Row Vector (1x3):\n", row_vector)

# Broadcasting addition: row_vector is expanded to match matrix shape
# ############## Your Code Here ##############
result = matrix + row_vector
# ############################################
print("\nMatrix + Row Vector (Broadcasting):\n", result)

# PyTorch automatically expanded the row_vector (shape 1x3) to shape 3x3 by duplicating rows, allowing element-wise addition with the matrix.


Matrix (3x3):
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Row Vector (1x3):
 tensor([[10, 11, 12]])

Matrix + Row Vector (Broadcasting):
 tensor([[11, 13, 15],
        [14, 16, 18],
        [17, 19, 21]])


In [ ]:
# Create a 3x3 tensor and a 3x1 tensor (column vector). Add them together.
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# ############## Your Code Here ##############
col_vector = torch.tensor([[10],[11],[12]])
# ############################################
print("\nMatrix (3x3):\n", matrix)
print("Column Vector (3x1):\n", col_vector)

# Broadcasting addition: col_vector is expanded to match matrix shape
# ############## Your Code Here ##############
result_col = matrix + col_vector
# ############################################
print("\nMatrix + Column Vector (Broadcasting):\n", result_col)


Matrix (3x3):
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Column Vector (3x1):
 tensor([[10],
        [11],
        [12]])

Matrix + Column Vector (Broadcasting):
 tensor([[11, 12, 13],
        [15, 16, 17],
        [19, 20, 21]])


### [5] Data Type Practice

Managing data types is important for memory efficiency and numerical stability.

In [ ]:
# Create a tensor of integers and check its dtype.
int_tensor = torch.tensor([1, 2, 3, 4])
print("\nInteger Tensor:", int_tensor)
# ############## Your Code Here ##############
print("Data Type:",int_tensor.dtype )
# ############################################

# Cast to int_tensor to float32
# ############## Your Code Here ##############
float_tensor = int_tensor.to(torch.float32)
# ############################################
print("\nConverted to Float Tensor:", float_tensor)
print("Data Type:", float_tensor.dtype)

# Create a floating-point tensor
float_tensor_orig = torch.tensor([1.1, 2.7, 3.5, 4.9])
print("\nOriginal Float Tensor:", float_tensor_orig)
# ############## Your Code Here ##############
print("Data Type:",float_tensor_orig.dtype )
# ############################################

# Cast float_tensor_orig to int32. Observe any changes.
# ############## Your Code Here ##############
int_tensor_cast = float_tensor_orig.to(torch.int32)
# ############################################
print("\nConverted to Integer Tensor:", int_tensor_cast)
print("Data Type:", int_tensor_cast.dtype)


Integer Tensor: tensor([1, 2, 3, 4])
Data Type: torch.int64

Converted to Float Tensor: tensor([1., 2., 3., 4.])
Data Type: torch.float32

Original Float Tensor: tensor([1.1000, 2.7000, 3.5000, 4.9000])
Data Type: torch.float32

Converted to Integer Tensor: tensor([1, 2, 3, 4], dtype=torch.int32)
Data Type: torch.int32


### [6] CPU vs GPU Practice

Moving tensors to the appropriate device (CPU or GPU) is necessary for leveraging hardware acceleration.

In [ ]:
# Set device to GPU
# ############## Your Code Here ##############
device = torch.device("cuda")
# ############################################
assert device == torch.device("cuda")
print(f"Using device: {device}")

# Create tensor (defaults to CPU unless specified otherwise)
cpu_tensor = torch.randn(2, 2)
print(f"\nTensor on CPU: {cpu_tensor.device}\n", cpu_tensor)

# Move to the GPU device
# ############## Your Code Here ##############
device_tensor = cpu_tensor.to(device)
# ############################################
print(f"\nTensor moved to {device_tensor.device}:\n", device_tensor)

# Move back to CPU explicitly
# ############## Your Code Here ##############
cpu_tensor_again = device_tensor.to("cpu")
# ############################################
print(f"\nTensor moved back to CPU: {cpu_tensor_again.device}\n", cpu_tensor_again)

# Perform an operation - requires tensors on the same device
if device_tensor.device != cpu_tensor.device:
    print("\nAdding tensors on different devices would cause an error.")
    # This would fail: cpu_tensor + device_tensor
    # Correct way:
    result_on_device = device_tensor + device_tensor
    print(f"Result of operation on {result_on_device.device}:\n", result_on_device)
else:
    print("\nBoth tensors are on the CPU, addition is fine.")
    result_on_cpu = cpu_tensor + cpu_tensor_again
    print(f"Result of operation on {result_on_cpu.device}:\n", result_on_cpu)

Using device: cuda

Tensor on CPU: cpu
 tensor([[-1.3527,  0.5018],
        [ 0.9626, -0.5458]])

Tensor moved to cuda:0:
 tensor([[-1.3527,  0.5018],
        [ 0.9626, -0.5458]], device='cuda:0')

Tensor moved back to CPU: cpu
 tensor([[-1.3527,  0.5018],
        [ 0.9626, -0.5458]])

Adding tensors on different devices would cause an error.
Result of operation on cuda:0:
 tensor([[-2.7054,  1.0035],
        [ 1.9252, -1.0915]], device='cuda:0')
